import Head from "next/head";

export function NextHead({title, description}){
    return (
        <Head>
            <title>{title ?? `${window.location.pathname}`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}