import Head from "next/head";

interface nextHeadProps {
    title?: string
    description?: string
}

export function NextHead({title, description}: nextHeadProps){
    return (
        <Head>
            <title>{title ?? `${window.location.pathname}`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}